name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: Install as local dependencies
        run: mvn --batch-mode --install
      - name: Build bungeeguard-universal
        run: cd bungeeguard-universal/ && mvn clean package
      - name: Upload bungeeguard-universal
      - run: mkdir staging && cp bungeeguard-universal/target/BungeeGuard.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging